### PR TITLE
8293824: gc/whitebox/TestConcMarkCycleWB.java failed "RuntimeException: assertTrue: expected true, was false"

### PR DESCRIPTION
**Pull request by kimbarrett**
Please review this change to WhiteBox and some tests involving G1 concurrent GCs.

Some tests currently use WhiteBox.g1StartConcMarkCycle() to trigger a
concurrent GC.  Many of them follow it with a loop waiting for a concurrent
cycle to not be in progress.  A few also preceed that call with a similar
loop, since that call does nothing and returns false if a concurrent cycle is
already in progress.  Those tests typically want to ensure there was a
concurrent cycle that was started after some setup.

The failing test calls that function, asserting that it returned true, e.g. a
new concurrent cycle was started.

There are various problems with this, due to races with concurrent cycles
started automatically, and due to possibly aborted (by full GCs) concurrent cycles,
making some of these tests unreliable in some configurations.

For example, the test failure associated with this bug intermittently arises
when running with `-Xcomp`, triggering a concurrent cycle before the explicit
request by the test, causing the explicit request to fail (because there is
already one in progress), failing the assert.  Waiting for there not to be an
in-progress cycle before the explicit request just narrows the race window.

We have a different mechanism in WhiteBox for controlling concurrent cycles,
the concurrent GC breakpoint mechanism.  By adding a counter specifically for
such cycles, we can use GC breakpoints to ensure only the concurrent cycles
the test wants are occurring, and can verify they completed successfully.

So we change tests using WhiteBox.g1StartConcMarkCycle() to instead use GC
breakpoints, along with the new WhiteBox.g1CompletedConcurrentMarkCycles() to
avoid racing request problems and to detect aborted cycles.  Since it is no
longer used, WhiteBox.g1StartConcMarkCycle() is removed.  The test that began
this adventure (TestConcMarkCycleWB.java) is also removed, since it no longer
serves any purpose, having been purely a test of that removed function.

Testing:
mach5 tier1-7 - running the changed tests on a variety of platforms with a
variety of configurations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293824](https://bugs.openjdk.org/browse/JDK-8293824): gc/whitebox/TestConcMarkCycleWB.java failed "RuntimeException: assertTrue: expected true, was false"

### Reviewers
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**) ⚠️ Review applies to [39abc3dc](https://git.openjdk.org/jdk20/pull/71/files/39abc3dc5aab088f7f3ca5a74c2fac0c529bd580)
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [39abc3dc](https://git.openjdk.org/jdk20/pull/71/files/39abc3dc5aab088f7f3ca5a74c2fac0c529bd580)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20 pull/71/head:pull/71` \
`$ git checkout pull/71`

Update a local copy of the PR: \
`$ git checkout pull/71` \
`$ git pull https://git.openjdk.org/jdk20 pull/71/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 71`

View PR using the GUI difftool: \
`$ git pr show -t 71`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20/pull/71.diff">https://git.openjdk.org/jdk20/pull/71.diff</a>

</details>

### CODE REVIEW

**Review by walulyai — APPROVED** [review]
Lgtm!

**Comment by kimbarrett** [comment]
BTW, after this change `GCCause::_wb_conc_mark` appears to no longer ever be issued.  I'm planning to remove it under the rubric of JDK-8235737.

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by kimbarrett** [comment]
Thanks for reviews @walulyai and @tschatzl .

**Pull request closed without merging**
