### PR TITLE
8300055: [BACKOUT] OPEN_MAX is no longer the max limit on macOS >= 10.6 for RLIMIT_NOFILE

### PR DESCRIPTION
**Pull request by gerard-ziemski**
This is a **backout** of [JDK-8291060 OPEN_MAX is no longer the max limit on macOS >= 10.6 for RLIMIT_NOFILE](https://bugs.openjdk.org/browse/JDK-8291060) which triggered a bug in ksh, resulting in a crash.

Verified with test case from https://bugs.openjdk.org/browse/JDK-8299258 and running Mach5 hs-tier1,2,3,4,5.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300055](https://bugs.openjdk.org/browse/JDK-8300055): [BACKOUT] OPEN_MAX is no longer the max limit on macOS >= 10.6 for RLIMIT_NOFILE

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20 pull/102/head:pull/102` \
`$ git checkout pull/102`

Update a local copy of the PR: \
`$ git checkout pull/102` \
`$ git pull https://git.openjdk.org/jdk20 pull/102/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 102`

View PR using the GUI difftool: \
`$ git pr show -t 102`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20/pull/102.diff">https://git.openjdk.org/jdk20/pull/102.diff</a>

</details>

### CODE REVIEW

**Review by tschatzl — APPROVED** [review]
Lgtm, and a complete backout of the original change. Feel free to push.

**Review by RogerRiggs — APPROVED** [review]

**Comment by gerard-ziemski** [comment]
Thank you @tschatzl and @RogerRiggs for speedy reviews. I will integrate as soon as I get go ahead from our gatekeeper.

**Comment by dcubed-ojdk** [comment]
> I will integrate as soon as I get go ahead from our gatekeeper.

Just FYI: You didn't need to wait for a gatekeeper to okay this. We're still in RDP1.
Even after we enter RDP2, it will be the release team that determines whether things
are approved. I do appreciate the heads up since I like to know what's going in this
late, but just an advisory is fine.

**Pull request closed without merging**
