### PR TITLE
8301206: Fix issue with LocaleData after JDK-8300719

### PR DESCRIPTION
**Pull request by DamonGuy**
Localization update didn't include an update to LocaleData file. This PR addresses this by updating the file with the newly translated values. The LocaleDataTest now passes. This should address the recent related failures to LocaleData.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301206](https://bugs.openjdk.org/browse/JDK-8301206): Fix issue with LocaleData after JDK-8300719

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20 pull/118/head:pull/118` \
`$ git checkout pull/118`

Update a local copy of the PR: \
`$ git checkout pull/118` \
`$ git pull https://git.openjdk.org/jdk20 pull/118/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 118`

View PR using the GUI difftool: \
`$ git pr show -t 118`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20/pull/118.diff">https://git.openjdk.org/jdk20/pull/118.diff</a>

</details>

### CODE REVIEW

**Review by naotoj — COMMENTED** [review]
The fix itself looks good. Add the bug id to `LocaleDataTest.java`

**Comment by DamonGuy** [comment]
> The fix itself looks good. Add the bug id to `LocaleDataTest.java`

Added BugID to the list of BugID's in `LocaleDataTest.java`

**Review by naotoj — APPROVED** [review]

**Pull request closed without merging**
