### PR TITLE
8298176: remove OpaqueZeroTripGuardPostLoop once main-loop disappears

### PR DESCRIPTION
**Pull request by eme64**
**Working on new fix... Will update this later**

We recently removed `Opaque2` nodes in [JDK-8294540](https://bugs.openjdk.org/browse/JDK-8294540). `Opaque2` nodes prevented some optimizations during loop-opts. The original idea was to prevent the use of both the un-incremented and incremented value of a loop phi after the loop, to reduce register pressure. But `Opaque2` also had the effect that the limit of the loop would not be optimized, which meant that the iv-value (entry value of phi) in post loop would never collapse (either to constant or TOP), but always remain a range. Now that `Opaque2` is gone, it can happen that when the main-loop disappears, the limit collapses. The zero-trip guard of the post-loop would be false, but does not collapse because of the `OpaqueZeroTripGuard`. The post-loop can half-collapse, leaving an inconsistent graph below the zero-trip guard if.

**Solution**
Have `OpaqueZeroTripGuardMainLoop` for main loop zero-trip guard, and `OpaqueZeroTripGuardPostLoop` for post-loop zero trip guard. Let `OpaqueZeroTripGuardPostLoop` remove itself once it cannot find the main-loop above it. We have these opaque nodes there to prevent collapsing of the zero-trip guards as long as the limits may still change, but after the main-loop is removed, no unrolling is done anymore, so the limit of the post-loop cannot change anymore, hence it is safe to remove the opaque node there.

An alternative approach was to let the main-loop remove the opaque node of the post-loop's zero-trip guard. But that does not work reliably, as the main-loop may get removed during PhaseCCP, and the main-loop is simply removed as "useless". Hence the LoopNode of the main-loop does not have a chance to detect its death during IGVN.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298176](https://bugs.openjdk.org/browse/JDK-8298176): remove OpaqueZeroTripGuardPostLoop once main-loop disappears ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20.git pull/22/head:pull/22` \
`$ git checkout pull/22`

Update a local copy of the PR: \
`$ git checkout pull/22` \
`$ git pull https://git.openjdk.org/jdk20.git pull/22/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22`

View PR using the GUI difftool: \
`$ git pr show -t 22`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20/pull/22.diff">https://git.openjdk.org/jdk20/pull/22.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk20/pull/22#issuecomment-1347893018)

### CODE REVIEW

**Comment by rwestrel** [comment]
OpaqueZeroTripGuardPostLoopNode::Identity() only runs if it's enqueued in the igvn workqueue, that is in the general case if its input changes. I'm not sure it's guaranteed that when the main loop looses its backedge for instance, the OpaqueZeroTripGuardPostLoopNode ends up being processed. The 2 feels like separate events. So I wonder if that fix is robust enough.

How does the main loop disappear during CCP? Is it still there but it's backedge is removed? Or is the entire loop removed? If that's the case, is that because of predicates?

**Comment by rwestrel** [comment]
It also feels like it's a problem that CCP calls Compile::disconnect_useless_nodes() and modifies the graph without letting igvn a chance to act on some graph change. Maybe that part should be revisited.

**Comment by eme64** [comment]
@rwestrel Thanks for the questions.
Only doing the check and removal in `OpaqueZeroTripGuardPostLoopNode::Identity()` would is unsafe if the inputs to that opaque node does not change after the main-loop disappears. Can that ever happen? I'm currently not sure. I will do some research on this and come back to you.
What I can say so far: all the cases which I have seen, and are in the regression test have the limit and the iv optimized down to a constant, in which case there is no way to ever change the result of that zero-trip-guard anyway.

**Comment by vnkozlov** [comment]
"The zero-trip guard of the post-loop would be false, but does not collapse because of the OpaqueZeroTripGuard. "
Can we just look only for this condition (guard is false) instead of looking through graph to see if main loop disappeared?

**Comment by eme64** [comment]
@vnkozlov The problem is that the zero-trip guard can be false for a while, because the post loop has no work. But then unrolling changes how much work the main loop does, and can give the post-loop work to do after all. That is the reason we have this opaque node in the first place. Without that opaque node, the condition could be false, we would remove the post loop. But then unrolling wants to give the post-loop some work, but it has already been optimized away.

**Comment by eme64** [comment]
This is an example of what happens with `test_001`:
Long loop -> loop-nest
inner loop of loop nest is PeelMainPost-ed
main loop is empty_loop -> removed
CCP after loop-opts:
detect that backedge of outer loop-nest is never taken.
Hence, initial value to PeelMainPost suddently changes to constant.
constant propagates through peeled iteration,
constant determines that zero-trip guard of main loop always goes to main loop
constant folds through empty_loop (previously main loop), exit value is now also constant.
constant arrives at zero-trip guard for post-loop, and also as the initial value for post loop.
Post-loop internals detect that that constant is outside trip-count phi range -> all becomes TOP.
But Opaque of zero trip guard protects the decay of the zero-trip guard.
End of CCP after loop-opts
Eventually, we have the if of the post-zero-trip guard with only one projection out (post loop projection has decayed).

**Comment by eme64** [comment]
@vnkozlov @rwestrel I am now very unsure about this fix myself.
On the one hand, I and Christian do not understand why the OpaqueZeroTripGuardPostLoopNode would be there in the first place:

This opaque and the iv of the post-loop take their input from the Phi that merges main-loop exit-value and pre-loop exit value (if zero-trip-guard of main decides to not enter main).

1. If this Phi ever decays to a constant: We can never change iv for post-loop.
2. If this Phi ever is a range, but a range outside the trip-count of the post-loop, then the post-loop phi will detect this, and replace itself with top, and deconstruct the loop from the inside. But the OpaqueZeroTripGuardPostLoopNode still guards the zero-trip-guard from decaying. We get an inconsistent graph.

So it seems to me we either guard both the iv and the zero-trip-guard or nothing. So far we don't really understand why there is that opaque, it is there for 22 years. Completely removing it could be a solution, but it is unclear if that is safe. Maybe it does something we are not aware of.

After re-analyzing, I cannot find a case where the main LoopNode is removed during CCP, it all seems to be during IGVN. So I can try out the fix Roland suggested: when the main LoopNode detects its removal, let it find (graph-walk to) the zero-trip-guard of the post-loop,  and remove the opaque node there. I'll need to see how easy that is, given that different things could have decayed during IGVN already, so the graph-walk could be a bit tricky.

**Comment by vnkozlov** [comment]
Based on comment and original changes it checks only iv from main loop exit and not Phi as you pointed:
```
  Node *incr  = main_end ->incr();
...
  // Step A2: Build a zero-trip guard for the post-loop.  After leaving the
  // main-loop, the post-loop may not execute at all.  We 'opaque' the incr
  // (the main-loop trip-counter exit value) because we will be changing
  // the exit value (via unrolling) so we cannot constant-fold away the zero
  // trip guard until all unrolling is done.

  Node *zer_opaq = new (2) OpaqueNode(incr);
```

It seems incorrect based on what you said and I think you can test your suggestion to completely remove it.

**Comment by vnkozlov** [comment]
Saying that, the current code looks the same. Where Phi comes from?

**Comment by eme64** [comment]
I think you are referring to the Phi that belongs to the region just above the post loop?
There we merge "main not taken" and "main exit".
I think that one is not created implicitly in `PhaseIdealLoop::insert_pre_post_loops`, but when the pre-loop is cloned from the main loop, we call `PhaseIdealLoop::fix_ctrl_uses`:
https://github.com/openjdk/jdk/blob/8c472e481676ed0ef475c4989477d5714880c59e/src/hotspot/share/opto/loopopts.cpp#L2511-L2513
It effectively merges the exit of the pre-loop (now zero trip guard of main loop) and the exit of the main-loop.

I had a conversation with @rwestrel yesterday. He also said that removing looks correct. But he was afraid that it would maybe still do something we are not aware of, just like with `Opaque2` which promised only to take care of register pressure, but in the end just blocked all these optimizations that can lead to post-loop removal (at least that is my current understanding).

One idea is to try and fix this by removing this `OpaqueZeroTripGuardPostLoopNode` once the main loop is gone for JDK20, and try for JDK21 to never even put it in. That way we'd have more time for testing. Once we are confident, we can backport the removal to JDK21.

**Comment by eme64** [comment]
We discussed it in the office with Christian and Tobias:
The issue is that the post-loop LoopNode is removed during CCP. The expectation so far was that they only are removed in IGVN, where in RegionNode::Ideal we catch the death of LoopNodes, and remove their `OpaqueZeroTripGuard` nodes above them.
But during CCP, we simply `remove useless` the LoopNode, and its opaque node stays behind. This leads to an inconsistent trip-guard if with only one projection, as the other projection would have lead down to the LoopNode.

We propose this point fix for JDK20:
We should check if's that sit on the boundary and have one projection removed: if they have an `OpaqueZeroTripGuard` (if they are a zero-trip-guard with opaque node), then we hack the condition value, which makes the if die properly during IGVN after CCP. This is in parallel to the removal logic in `RegionNode::Ideal`.

For JDK21 I will also file an RFE to try removing the `OpaqueZeroTripGuardPostLoop` completely (never even insert it).

**Comment by rwestrel** [comment]
> For JDK21 I will also file an RFE to try removing the `OpaqueZeroTripGuardPostLoop` completely (never even insert it).

FWIW, I don't think it's the right way to proceed. Having `OpaqueZeroTripGuardPostLoop` guarantees the zero trip guard for the post loop doesn't go away while we're not done with that loop. It's quite possible the zero trip guard without `OpaqueZeroTripGuardPostLoop` can't fold away either because C2 in its current state can't prove anything about it or because other opaque nodes hide enough type information. It's also possible it can fold away but current testing won't catch it. All sort of questions we don't have to think about as long as `OpaqueZeroTripGuardPostLoop`  is here: having `OpaqueZeroTripGuardPostLoop` makes reasoning about the loops easier at the very least. That seems like a precious thing that we would give up only because there's a corner case that's bothering us today.

**Pull request closed without merging**
