### PR TITLE
8298976: ProblemList java/util/concurrent/ExecutorService/CloseTest.java on macosx-aarch64

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
A batch a trivial fixes to ProblemList tests:
[JDK-8298976](https://bugs.openjdk.org/browse/JDK-8298976) ProblemList java/util/concurrent/ExecutorService/CloseTest.java on macosx-aarch64
[JDK-8298977](https://bugs.openjdk.org/browse/JDK-8298977) ProblemList vmTestbase/nsk/stress/strace/strace002.java on 2 platforms
[JDK-8298978](https://bugs.openjdk.org/browse/JDK-8298978) ProblemList vmTestbase/nsk/stress/strace/strace003.java on 2 platforms

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8298976](https://bugs.openjdk.org/browse/JDK-8298976): ProblemList java/util/concurrent/ExecutorService/CloseTest.java on macosx-aarch64
 * [JDK-8298977](https://bugs.openjdk.org/browse/JDK-8298977): ProblemList vmTestbase/nsk/stress/strace/strace002.java on 2 platforms
 * [JDK-8298978](https://bugs.openjdk.org/browse/JDK-8298978): ProblemList vmTestbase/nsk/stress/strace/strace003.java on 2 platforms

### Reviewers
 * [Kim Barrett](https://openjdk.org/census#kbarrett) (@kimbarrett - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20 pull/50/head:pull/50` \
`$ git checkout pull/50`

Update a local copy of the PR: \
`$ git checkout pull/50` \
`$ git pull https://git.openjdk.org/jdk20 pull/50/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 50`

View PR using the GUI difftool: \
`$ git pr show -t 50`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20/pull/50.diff">https://git.openjdk.org/jdk20/pull/50.diff</a>

</details>

### CODE REVIEW

**Review by kimbarrett — APPROVED** [review]
Looks good.

**Comment by dcubed-ojdk** [comment]
@kimbarrett - Thanks for the fast review!

/integrate

**Review by irisclark — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@irisclark - Thanks for the review! You may not be listed on the integration
depending on how the bots are running.

**Comment by AlanBateman** [comment]
Instead of excluding java/util/concurrent/ExecutorService/CloseTest.java, we can just comment out the line in the test's DataProvider that produces a ForkJoinPool. That will allow the t test to exercise the other implementations until ForkJoinPool shutdown issue is fixed.

**Comment by dcubed-ojdk** [comment]
@AlanBateman - It's only ProblemListed on one platform...

**Pull request closed without merging**
