### PR TITLE
8300141: ProblemList java/util/concurrent/locks/Lock/OOMEInAQS.java with ZGC

### PR DESCRIPTION
**Pull request by dcubed-ojdk**
Trivial fixes to ProblemList some tests:
[JDK-8300141](https://bugs.openjdk.org/browse/JDK-8300141) ProblemList java/util/concurrent/locks/Lock/OOMEInAQS.java with ZGC
[JDK-8300144](https://bugs.openjdk.org/browse/JDK-8300144) ProblemList vmTestbase/nsk/sysdict/vm/stress/chain/chain007/chain007.java with ZGC
[JDK-8300147](https://bugs.openjdk.org/browse/JDK-8300147) ProblemList vmTestbase/nsk/jvmti/SetFieldModificationWatch/setfmodw001/TestDescription.java in Xcomp

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8300141](https://bugs.openjdk.org/browse/JDK-8300141): ProblemList java/util/concurrent/locks/Lock/OOMEInAQS.java with ZGC
 * [JDK-8300144](https://bugs.openjdk.org/browse/JDK-8300144): ProblemList vmTestbase/nsk/sysdict/vm/stress/chain/chain007/chain007.java with ZGC
 * [JDK-8300147](https://bugs.openjdk.org/browse/JDK-8300147): ProblemList vmTestbase/nsk/jvmti/SetFieldModificationWatch/setfmodw001/TestDescription.java in Xcomp

### Reviewers
 * [Mikael Vidstedt](https://openjdk.org/census#mikael) (@vidmik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20 pull/103/head:pull/103` \
`$ git checkout pull/103`

Update a local copy of the PR: \
`$ git checkout pull/103` \
`$ git pull https://git.openjdk.org/jdk20 pull/103/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 103`

View PR using the GUI difftool: \
`$ git pr show -t 103`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20/pull/103.diff">https://git.openjdk.org/jdk20/pull/103.diff</a>

</details>

### CODE REVIEW

**Review by vidmik — APPROVED** [review]

**Comment by dcubed-ojdk** [comment]
@vidmik - Thanks for the fast review!

**Pull request closed without merging**
